### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by xxidbr9** [xxidbr9/ajaib-interview-test#16]
### TODO
- [ ] Create Presentation using google slides
- [x] Better Readme

**Comment by syukronarie** [comment]
Once presentation done, please arrange session with me ah.. 🤝

Happy coding!

**Comment by xxidbr9** [comment]
> Once presentation done, please arrange session with me ah.. 🤝
> 
> Happy coding!

hahah sure, will happy to present that 😂😂✨
